<a href="https://colab.research.google.com/github/emi199111/data-science-bootcamp/blob/main/01_wprowadzenie/1lekcja.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [2]:
import numpy as np
np.__version__

'1.25.2'

In [3]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals'

In [ ]:
help(np.array)

In [10]:
x=np.array([1, 3])
print(type(x))

<class 'numpy.ndarray'>


In [12]:
x.ndim

1

In [13]:
x.shape

(2,)

In [14]:
x.size

2

In [16]:
x.dtype

dtype('int64')

In [18]:
x=np.array([1.3, 2.6, 4.6])
print(x)

[1.3 2.6 4.6]


In [19]:
x.dtype

dtype('float64')

2D array

In [21]:
x=np.array([[1,2],[-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [23]:
x.ndim


2

In [24]:
x.shape

(2, 2)

In [27]:
x=np.array([[1,2,3], [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
x.shape

(2, 3)

In [28]:
x.ndim

2

3D array

In [31]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],

      [[4,1,3],
       [4,2,1]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [32]:
x.ndim

3

In [33]:
x.shape

(2, 2, 3)

Braki danych

tworzenie tablic


In [37]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [39]:
np.ones(shape=(5,5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [42]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [43]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [47]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [48]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [50]:
A= np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [51]:
A.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [53]:
A.reshape((5,-1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Podstawowe operacje na tablicach

In [55]:
A= np.array([3, 1, 4, 2])
B= np.array([3, -3, 3, 2])

print(A)
print(B)

[3 1 4 2]
[ 3 -3  3  2]


In [56]:
A+B

array([ 6, -2,  7,  4])

In [57]:
A-B

array([0, 4, 1, 0])

In [58]:
A*B

array([ 9, -3, 12,  4])

In [59]:
A/B

array([ 1.        , -0.33333333,  1.33333333,  1.        ])

In [62]:
np.add(A,B)

array([ 6, -2,  7,  4])

In [63]:
np.subtract(A,B)

array([0, 4, 1, 0])

In [65]:
np.divide(A,B)

array([ 1.        , -0.33333333,  1.33333333,  1.        ])

In [64]:
np.multiply(A,B)


array([ 9, -3, 12,  4])

In [60]:
A+3

array([6, 4, 7, 5])

In [61]:
A*2

array([6, 2, 8, 4])

mnozenie macierzy

In [67]:
X = np.array([[1,3],[-2,0]])
Y = np.array([[6,0],[-1,2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [68]:
X*Y

array([[6, 0],
       [2, 0]])

In [69]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [70]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [71]:
X @ Y

array([[  3,   6],
       [-12,   0]])

Generowanie liczb pseudolosowych

In [4]:
np.random.seed(0)

In [6]:
np.random.randn()

1.764052345967664

In [7]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [11]:
np.random.randn(10,4)

array([[ 0.02135122, -0.91911344,  0.19275385, -0.36505522],
       [-1.79132755, -0.05858655, -0.31754309, -1.6324233 ],
       [-0.06713415,  1.48935596,  0.52130375,  0.61192719],
       [-1.34149673,  0.47689837,  0.14844958,  0.52904524],
       [ 0.42262862, -1.35978073, -0.04140081, -0.75787086],
       [-0.05008409, -0.89740093,  1.31247037, -0.85897239],
       [-0.89894216,  0.07458641, -1.07709907, -0.4246633 ],
       [-0.8299646 ,  1.41117206,  0.78580383, -0.05746952],
       [-0.39121705,  0.94091761,  0.40520408,  0.4980524 ],
       [-0.02619224, -1.68823003, -0.11246598, -0.53248992]])

In [12]:
np.random.rand()

0.3106292182913063

In [13]:
np.random.rand(10,2)

array([[7.91227431e-01, 7.15143252e-01],
       [5.58051237e-01, 7.04948062e-01],
       [4.18636864e-01, 5.31004761e-03],
       [1.13551285e-02, 5.11221788e-01],
       [8.32909797e-02, 5.10754802e-02],
       [9.65516639e-01, 8.59002640e-01],
       [1.52027227e-01, 6.64218590e-04],
       [9.41667795e-01, 2.78325298e-01],
       [1.85897603e-01, 6.91508108e-01],
       [1.08903739e-01, 2.64649598e-01]])

In [16]:
np.random.randint(low=10, high=15, size=10)

array([11, 13, 13, 13, 14, 12, 11, 10, 10, 10])

In [18]:
np.random.choice([4,1,1,7,9,10])

1

In [19]:
np.random.choice(["python", 'java', 'sql'])

'sql'

In [22]:
data=np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.random.shuffle(data)

In [27]:
data

array([7, 8, 4, 1, 2, 5, 3, 6, 0, 9])

POdstawowae funkcje

In [30]:
np.exp(1)

2.718281828459045

In [31]:
np.sqrt(9)

3.0

In [33]:
np.all([2,3,0])

False

In [34]:
np.any([1,2,1])

True

In [35]:
np.any([0,0,0])

False

In [37]:
A=np.random.rand(5)
A

array([0.20868333, 0.37535043, 0.64113293, 0.71603265, 0.05637216])

In [38]:
np.argmax(A)

3

In [39]:
A[np.argmax(A)]

0.7160326485544439

In [40]:
np.argmin(A)

4

In [42]:
np.argsort(A)

array([4, 0, 1, 2, 3])

In [43]:
np.max(A)

0.7160326485544439

In [44]:
np.min(A)


0.056372162119019076

In [45]:
np.mean(A)
#średnia

0.39951430074524674

In [46]:
np.median(A)
#mediana

0.3753504318273384

In [47]:
np.std(A)
#odchylenie standardowe

0.2503239128728869

INDEKSOWANIE WYCINANIE

In [50]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [51]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [53]:
A[2]

2

In [54]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [55]:
A[:2]

array([0, 1])

In [56]:
#wycina konkretne indeksy
A[[0,2]]

array([0, 2])

In [57]:
A[-1]

19

In [58]:
A[10:15]

array([10, 11, 12, 13, 14])

In [60]:
A=A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [61]:
A[0]

array([0, 1, 2, 3, 4])

In [62]:
A[1]

array([5, 6, 7, 8, 9])

In [64]:
#wycinanie kolumny

A[:,-1]

array([ 4,  9, 14, 19])

In [65]:
#wycinanie konkretnej pozycji

A[1,1]

6

In [68]:
#wycinanie fragmentu macierzy

A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [70]:
A[1,2]=14

In [71]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

iteracja po tablicach

In [72]:
A


array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [74]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [75]:
#iterowanie tanlicy element po elemencie

for item in A.flat:
    print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


ZMIANA ROZMIARU TABLIC


In [76]:
A.shape

(4, 5)

In [79]:
A.reshape(4,-1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [80]:
A.shape

(4, 5)

In [82]:
A.ravel()
#przeciwienstwo metody reshape ...umozliwia wyplaszczenie macierzy do postaci 1 wymiarowej

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [83]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [84]:
#transpozycja macierzy (zamiana wymiarow - kolumna na wiersz)
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

MASKI LOGICZNE

In [86]:
B=np.arange(start=-10, stop=10, step=0.5)
B

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [87]:
B>0

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [89]:
B[B>0]
#maski moga sluzyc do wycinania interesujacych elementow tablic

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [90]:
#laczenie warunkow w maskach
#ponizszy kod wygeneruje blad

B[B>-5andB<5]

SyntaxError: invalid decimal literal (<ipython-input-90-449486ead635>, line 3)

In [93]:
#aby laczyc awrunki operacji logicznych may szereg odpowiednich metod np:

M=np.bitwise_and(B>-5, B<5)

In [92]:
#taka maske moemy wykorzystac  w wcinaniu fragmentu

In [94]:
B[M]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])