<a href="https://colab.research.google.com/github/emi199111/data-science-bootcamp/blob/main/Algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np


Norma wektora w R2

In [5]:
#tworzymy wektor
v1=np.array([-1,4])
v1

array([-1,  4])

In [6]:
np.linalg.norm(v1)

4.123105625617661

Norma wektora Rn

In [7]:
v2= np.array([-10,10,13])
v2

array([-10,  10,  13])

In [8]:
np.linalg.norm(v2)

19.209372712298546

odleglosc 2 punktow na plaszczyznie

In [4]:
p=np.array([3,0])
q=np.array([0,4])

np.linalg.norm(p-q)

5.0

odleglosc punktow w przestrzeni R3

In [5]:
p=np.array([3,0, 1])
q=np.array([0,4,2])

np.linalg.norm(p-q)

5.0990195135927845

Mnozenie macierzy

In [8]:
X= np.array([[5,3],[3,9]])
Y = np.array([1, -1])
Z=X.dot(Y)
Z

array([ 2, -6])

aby moc przemnozyc ze soa macierze ro liczba kolumn lewej kolumny misi sie zgadzac z liczba wierszy prawej kolumny

In [9]:
X = np.array([[2, -1, 3], [3,1,0]])
Y = np.array([[2,1,-1],
              [0,-1,2],
              [3,2,0]])
print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [11]:
np.dot(X,Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

WWYZNACZNIK MACIERZY

In [12]:
A = np.array([[2,4], [-1,3]])

np.linalg.det(A)

9.999999999999998

ASLAD MACIERZY - suma eleentow na przekatnej macierzy

In [13]:
np.trace(A)

5

MACIERZ JEDNOSTKOWA
to macierz kwadratowa to macierz ktora ma jedynki po przekatnej

In [14]:
Z = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(Z)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [15]:
# MACIERZ JEDNOSTKOWA MOZNA WYGENEROWAC ROWNIEZ ZA POOCA METODY np.eye()

np.eye(3, dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

MACIERZ ODWROTNA
macierz kwadratowa stopnia n taka ze AB=BA=I(macierz jednostkowa)

In [17]:
A


array([[ 2,  4],
       [-1,  3]])

In [18]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [23]:
np.set_printoptions(precision=4, suppress=True)
np.dot(A,B)

array([[1., 0.],
       [0., 1.]])

MACIERZ TRANSPONOWANA
-zamiana wierszy na kolumny i kolumny na wiersze

In [24]:
A.T

array([[ 2, -1],
       [ 4,  3]])

In [25]:
A = np.array = [[2,4],[1,-1]]
B = np.array = [[10], [-1]]

print(A, '\n')
print(B)

[[2, 4], [1, -1]] 

[[10], [-1]]


In [27]:
#szukamy macierzy odwrotnej do macierzy A

A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.1667  0.6667]
 [ 0.1667 -0.3333]]


In [29]:
X = np.dot(A_inv, B)
print(X)

[[1.]
 [2.]]
